<article id="cv-preview" class="tp-paper cv-yellow-paper relative overflow-hidden bg-white shadow-xl ring-1 ring-slate-200">
    <div class="cv-yellow-sidebar relative z-10 px-6 pb-7 pt-7 text-white sm:px-8">
        <div class="cv-yellow-corner" aria-hidden="true"></div>
        <div class="relative z-10 flex items-center gap-4">
            <div class="cv-yellow-photo grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-full text-2xl font-black">
                <template x-if="cv.photo"><img :src="cv.photo" alt="Profile photo" class="h-full w-full object-cover"></template>
                <span x-show="!cv.photo" x-text="initials()"></span>
            </div>
            <div class="min-w-0"><p class="mb-1 text-[.58rem] font-bold uppercase tracking-[.2em] text-[#f4c400]" x-text="cv.headline || 'Professional title'"></p><h2 class="break-words text-2xl font-black uppercase leading-tight" x-text="cv.name || 'Your Name'"></h2></div>
        </div>
    </div>
    <div class="cv-yellow-layout relative z-10">
        <aside class="cv-yellow-aside space-y-6 bg-[#222222] px-6 py-7 text-white sm:px-7">
            <section><h3 class="cv-yellow-side-heading">Contact me</h3><div class="space-y-2 text-[.65rem] leading-relaxed text-slate-300"><p x-show="cv.phone" class="flex gap-2"><span class="cv-yellow-icon">☎</span><span x-text="cv.phone"></span></p><p x-show="cv.email" class="flex gap-2 break-all"><span class="cv-yellow-icon">✉</span><span x-text="cv.email"></span></p><p x-show="cv.location" class="flex gap-2"><span class="cv-yellow-icon">⌖</span><span x-text="cv.location"></span></p><p x-show="cv.website" class="flex gap-2 break-all"><span class="cv-yellow-icon">↗</span><span x-text="cv.website"></span></p><p x-show="cv.linkedin" class="flex gap-2 break-all"><span class="cv-yellow-icon font-bold">in</span><span x-text="cv.linkedin"></span></p></div></section>
            <section><h3 class="cv-yellow-side-heading">Education</h3><div class="space-y-4"><template x-for="item in cv.education" :key="item.id"><div x-show="item.degree || item.institution"><p class="text-[.68rem] font-bold text-white" x-text="item.degree || 'Degree name'"></p><p class="mt-1 text-[.63rem] text-[#f4c400]" x-text="item.institution"></p><p class="text-[.6rem] text-slate-400" x-text="[item.startYear, item.endYear].filter(Boolean).join(' – ')"></p></div></template><p x-show="!cv.education.some(item => item.degree || item.institution)" class="text-[.65rem] text-slate-500">Education will appear here.</p></div></section>
            <section><h3 class="cv-yellow-side-heading">Expertise</h3><div class="grid grid-cols-2 gap-x-3 gap-y-2 text-[.64rem] text-slate-300"><template x-for="skill in skillList()" :key="'expertise-' + skill"><span class="flex items-center gap-2"><span class="h-1.5 w-1.5 shrink-0 rounded-full bg-[#f4c400]"></span><span x-text="skill"></span></span></template><p x-show="!skillList().length" class="text-slate-500">Add skills in the editor.</p></div></section>
            <section x-show="cv.settings.referenceMode === 'full' && cv.references.some(item => item.name)"><h3 class="cv-yellow-side-heading">Reference</h3><div class="space-y-3 text-[.63rem] text-slate-300"><template x-for="item in cv.references" :key="item.id"><div x-show="item.name"><p class="font-bold text-white" x-text="item.name"></p><p x-text="[item.position, item.company].filter(Boolean).join(' · ')"></p><p x-text="[item.phone, item.email].filter(Boolean).join(' · ')"></p></div></template></div></section>
        </aside>
        <div class="cv-yellow-main space-y-7 px-6 py-7 sm:px-8">
            <section><h3 class="cv-yellow-main-heading"><span class="cv-yellow-dot">✦</span> About me</h3><p class="cv-yellow-copy" x-text="cv.summary || 'Your professional summary will appear here. Add a focused introduction that shows your strengths and direction.'"></p></section>
            <section><h3 class="cv-yellow-main-heading"><span class="cv-yellow-dot">✦</span> Work experience</h3><div class="space-y-5"><template x-for="item in cv.experience" :key="item.id"><div x-show="item.position || item.company" class="cv-yellow-entry"><div class="flex items-start justify-between gap-3"><div><p class="text-[.75rem] font-extrabold uppercase text-[#222222]" x-text="item.position || 'Job title'"></p><p class="mt-1 text-[.63rem] font-bold text-[#f4a900]" x-text="[item.company, item.location].filter(Boolean).join(' · ')"></p></div><span class="shrink-0 text-[.6rem] font-semibold text-slate-400" x-text="[item.startDate, item.current ? 'Present' : item.endDate].filter(Boolean).join(' – ')"></span></div><p x-show="item.description" class="cv-yellow-copy mt-2 whitespace-pre-line" x-text="item.description"></p></div></template><p x-show="!cv.experience.some(item => item.position || item.company)" class="cv-yellow-copy text-slate-400">Your work experience will appear here.</p></div></section>
            <section><h3 class="cv-yellow-main-heading"><span class="cv-yellow-dot">✦</span> Skills</h3><div class="grid gap-x-6 gap-y-4 sm:grid-cols-2"><template x-for="item in cv.skills" :key="item.id"><div x-show="item.name"><div class="flex items-center justify-between text-[.63rem] font-bold text-slate-700"><span x-text="item.name"></span><span x-text="item.level || 'Professional'"></span></div><div class="mt-1 h-1.5 overflow-hidden rounded-full bg-slate-200"><div class="h-full rounded-full bg-[#f4c400]" :style="`width: ${item.level === 'Expert' ? 100 : item.level === 'Advanced' ? 90 : item.level === 'Professional' ? 80 : item.level === 'Intermediate' ? 65 : 45}%`"></div></div></div></template><p x-show="!cv.skills.some(item => item.name)" class="cv-yellow-copy text-slate-400">Add skills and proficiency levels.</p></div></section>
            <section x-show="cv.projects.some(item => item.name) || cv.certifications.some(item => item.name)"><h3 class="cv-yellow-main-heading"><span class="cv-yellow-dot">✦</span> Additional</h3><div class="grid gap-4 sm:grid-cols-2"><template x-for="item in cv.projects" :key="'project-' + item.id"><div x-show="item.name"><p class="text-[.7rem] font-bold" x-text="item.name"></p><p class="cv-yellow-copy" x-text="item.description"></p></div></template><template x-for="item in cv.certifications" :key="'cert-' + item.id"><div x-show="item.name"><p class="text-[.7rem] font-bold" x-text="item.name"></p><p class="cv-yellow-copy" x-text="[item.organization, item.issueDate || item.date].filter(Boolean).join(' · ')"></p></div></template></div></section>
        </div>
    </div>
</article>
