<article id="cv-preview" class="tp-paper relative overflow-hidden bg-white shadow-xl ring-1 ring-slate-200">
    <div class="tp-watermark" aria-hidden="true"><span x-text="((cv.name || 'Your Name').trim()) + ' CV'"></span></div>
    <header class="tp-header relative z-10 bg-[#0f172a] px-7 pb-6 pt-7 text-white sm:px-10"><div class="flex items-center gap-5"><div class="grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-full bg-slate-700 text-2xl font-black"><template x-if="cv.photo"><img :src="cv.photo" alt="Profile photo" class="h-full w-full rounded-full object-cover"></template><span x-show="!cv.photo" x-text="initials()"></span></div><div class="min-w-0"><p class="mb-1 text-[.6rem] font-bold uppercase tracking-[.22em] text-slate-300" x-text="cv.headline || 'Professional title'"></p><h2 class="break-words text-3xl font-extrabold leading-tight" x-text="cv.name || 'Your Name'"></h2></div></div></header>
    <div class="tp-body relative z-10 space-y-5 px-7 py-7 sm:px-10">
        <section><h3 class="tp-heading">Professional Summary</h3><p class="tp-copy" x-text="cv.summary || 'Your professional summary will appear here.'"></p></section>
        <section x-show="cv.experience.some(item => item.position || item.company)"><h3 class="tp-heading">Experience</h3><div class="space-y-4"><template x-for="item in cv.experience" :key="item.id"><div x-show="item.position || item.company"><p class="tp-title" x-text="item.position || 'Job position'"></p><p class="tp-meta" x-text="[item.company, item.location, item.startDate, item.current ? 'Present' : item.endDate].filter(Boolean).join(' · ')"></p><p x-show="item.description" class="tp-copy whitespace-pre-line" x-text="item.description"></p></div></template></div></section>
        <section x-show="cv.projects.some(item => item.name)"><h3 class="tp-heading">Projects</h3><div class="space-y-4"><template x-for="item in cv.projects" :key="item.id"><div x-show="item.name"><p class="tp-title" x-text="item.name"></p><p class="tp-meta" x-text="[item.role, item.technologies].filter(Boolean).join(' / ')"></p><p x-show="item.description" class="tp-copy whitespace-pre-line" x-text="item.description"></p></div></template></div></section>
        <section x-show="cv.education.some(item => item.degree || item.institution)"><h3 class="tp-heading">Education</h3><div class="space-y-3"><template x-for="item in cv.education" :key="item.id"><div x-show="item.degree || item.institution"><p class="tp-title" x-text="[item.degree, item.field].filter(Boolean).join(' / ')"></p><p class="tp-meta" x-text="[item.institution, item.location, [item.startYear, item.endYear].filter(Boolean).join(' – ')].filter(Boolean).join(' · ')"></p></div></template></div></section>
        <section x-show="skillList().length"><h3 class="tp-heading">Skills</h3><div class="flex flex-wrap gap-2"><template x-for="skill in skillList()" :key="'skill-'+skill"><span class="tp-tag" x-text="skill"></span></template></div></section>
        <section x-show="cv.certifications.some(item => item.name)"><h3 class="tp-heading">Certifications</h3><template x-for="item in cv.certifications" :key="item.id"><div x-show="item.name"><p class="tp-title" x-text="item.name"></p><p class="tp-meta" x-text="[item.organization, item.issueDate || item.date].filter(Boolean).join(' · ')"></p></div></template></section>
        <section x-show="cv.languages.some(item => item.name)"><h3 class="tp-heading">Languages</h3><p class="tp-copy"><template x-for="(item, index) in cv.languages" :key="item.id"><span x-show="item.name"><b x-text="item.name"></b><span x-text="(item.proficiency || item.level) ? ' · ' + (item.proficiency || item.level) : ''"></span><span x-show="index < cv.languages.length - 1">, </span></span></template></p></section>
    </div>
    <footer class="tp-footer relative z-10 h-1.5 bg-[#3b82f6]"></footer>
</article>
